
title: <p align="center"> Vamshi </p>
logo: /assets/img/vamshi.JPG

description:
 
  
  <br>   
  I'm currently working with Infosys as a PeopleSoft developer.I have 14 years of experience in IT
  <br>
  </p>



theme: jekyll-theme-minimal
